### Variabili
@basseUrl = http://localhost:8080/api/auth/users
@Content-Type= application/json

### 1. Register
POST {{basseUrl}}/register
content-type : {{Content-Type}}

{
    "name": "sample name",
    "surname": "sample surname",
    "email": "sample@example.com",
    "password": "samplepassword"
}


### 2. Login
POST {{basseUrl}}/login
content-type : {{Content-Type}}

{
    "email": "sample@example.com",
    "password": "samplepassword"
}

### 3. Get current user
GET {{basseUrl}}/profile

curl -c cookies.txt -X POST http://localhost:8080/api/auth/users/login \
-H "Content-Type: application/json" \ 
-d '{"email": "sample@example.com","password": "samplepassword"}'




curl -c cookies.txt -X POST http://localhost:8080/api/auth/users/login \-H "Content-Type: application/json" \-d '{"email": "sample@example.com","password": "samplepassword"}'
curl -b cookies.txt -X GET http://localhost:8080/api/auth/users/me
