# Spring Boot Application Properties
spring.application.name=BackEnd
server.port=8080
server.servlet.context-path=/api
server.servlet.session.timeout=30m
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.path=/api
server.servlet.session.cookie.http-only=true
server.servlet.session.tracking-modes=cookie


#DB CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/FileHubDB
spring.datasource.username=root
spring.datasource.password=rootpassword

#JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



#LOG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB